# Cloud Build: build, push, deploy VaultMesh Workbench to Cloud Run (main only)
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

substitutions:
  _REGION: europe-west1
  _REPO: vaultmesh
  _SERVICE: vaultmesh-workbench
  _PORT: '8787'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/workbench:${SHORT_SHA}'

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: context
    entrypoint: bash
    args:
      - -euxo
      - pipefail
      - -c
      - |
        echo "PROJECT_ID=$PROJECT_ID"
        echo "BRANCH_NAME=${BRANCH_NAME:-<none>}"
        echo "TAG_NAME=${TAG_NAME:-<none>}"
        echo "COMMIT_SHA=$COMMIT_SHA"
        echo "SHORT_SHA=$SHORT_SHA"

  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args:
      - build
      - '-f'
      - 'workbench/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/workbench:${SHORT_SHA}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/workbench:${SHORT_SHA}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy-if-main
    entrypoint: bash
    args:
      - -euxo
      - pipefail
      - -c
      - |
        if [[ "${BRANCH_NAME:-}" == "main" ]]; then
          echo "Deploying ${_SERVICE} to Cloud Run in ${_REGION}..."
          gcloud run deploy "${_SERVICE}" \
            --image="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/workbench:${SHORT_SHA}" \
            --region="${_REGION}" \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=PORT=${_PORT} \
            --quiet
        else
          echo "Branch '${BRANCH_NAME:-}' is not main; skipping deploy."
        fi
