name: Setup Node + pnpm
description: Install Node.js and pnpm, echo versions, and install workspace deps
inputs:
  node-version:
    description: Node.js version
    default: '20'
  pnpm-version:
    description: pnpm version
    default: '10.17.0'
  install-args:
    description: Args passed to `pnpm -w install`
    default: '--frozen-lockfile'
  cache:
    description: Cache type for setup-node (pnpm | npm | yarn | '')
    default: 'pnpm'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Show tool versions
      shell: bash
      run: |
        node -v
        pnpm -v

    - name: Install workspace deps
      shell: bash
      run: pnpm -w install ${{ inputs.install-args }}
