steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/forge/ai-companion-proxy:$BUILD_ID", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/forge/ai-companion-proxy:$BUILD_ID"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "ai-companion-proxy",
        "--image", "${_REGION}-docker.pkg.dev/$PROJECT_ID/forge/ai-companion-proxy:$BUILD_ID",
        "--region", "${_REGION}",
        "--service-account", "ai-companion-proxy@$PROJECT_ID.iam.gserviceaccount.com",
        "--memory", "512Mi",
        "--cpu", "1",
        "--set-env-vars", "TARGET_BASE=https://cloudaicompanion.googleapis.com",
        "--concurrency", "5",
        "--min-instances", "0",
        "--max-instances", "30"
      ]
substitutions:
  _REGION: "europe-west3"
# Note: omit images:[] to avoid parse errors when using local submits without VCS
