name: nightly-security
on:
  schedule: [{ cron: "17 1 * * *" }]   # 01:17 UTC daily
  workflow_dispatch: {}
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install
      - run: pnpm run build
      - name: Install gitleaks for secrets scan
        run: |
          if ! command -v gitleaks >/dev/null; then pnpm dlx gitleaks >/dev/null 2>&1 || true; fi
      - name: Run prepush gates (FAST)
        env: { FORGE_FAST: "1" }
        run: pnpm run ci:gates
      - name: Synthesize metrics.json
        run: |
          mkdir -p artifacts/prepush
          jq -nc \
            --slurpfile sec artifacts/prepush/secrets_audit.json \
            --slurpfile rev artifacts/prepush/code_review.json \
            '{ ts: (now|todate),
               secrets_critical: ($sec[0].result.summary.critical // 0),
               review_high: ($rev[0].result.summary.high // 0) }' \
            > artifacts/prepush/metrics.json
      - uses: actions/upload-artifact@v4
        with:
          name: nightly-security
          path: artifacts/prepush/metrics.json
          if-no-files-found: ignore
