name: pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/SALES/**'
      - '.github/workflows/pages.yml'
      - 'package.json'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build sales artifacts (deck + one-pager)
        run: |
          npm run sales:build
          # copy demo to dist
          mkdir -p dist/demo
          cp -R docs/SALES/demo/* dist/demo/
          # ensure index exists
          mkdir -p dist
          cp dist/sales-deck.html dist/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4