name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CI placeholder
        run: |
          echo "CI green: placeholder workflow"
          echo "Repo: $GITHUB_REPOSITORY"

