name: forge-ci
on:
  push:
  pull_request:
  tags: [ 'v*' ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        run: corepack enable || true && pnpm -v || npm i -g pnpm@9

      - name: Install
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Lint & Typecheck
        run: |
          pnpm run -r lint || true
          pnpm run -r typecheck || true

      - name: Tests
        run: pnpm -r test || pnpm test || true

      - name: Witness
        run: node ./scripts/witness.js

      - name: Rollup
        run: ./scripts/rollup.sh

      - name: Link to previous root
        run: ./scripts/root-link.sh

      - name: Upload receipts
        uses: actions/upload-artifact@v4
        with:
          name: receipts-${{ github.sha }}
          path: |
            receipts/ROOT.txt
            receipts/**/*.json
            ROLLUP.txt
          if-no-files-found: warn

      - name: Summary
        run: |
          set -euo pipefail
          echo "### Forge — Provenance" >> "$GITHUB_STEP_SUMMARY"
          echo "- Commit: ${GITHUB_SHA}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Root: $(grep '^root:' receipts/ROOT.txt | awk '{print $2}')" >> "$GITHUB_STEP_SUMMARY"

  sign-root:
    needs: [smoke]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Rebuild ROOT if missing
        run: test -f receipts/ROOT.txt || ./scripts/rollup.sh

      - name: Import GPG key
        if: ${{ secrets.GPG_PRIVATE_KEY != '' }}
        run: echo "${GPG_PRIVATE_KEY}" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Sign ROOT (GPG)
        if: ${{ secrets.GPG_PRIVATE_KEY != '' }}
        run: |
          gpg --batch --yes --pinentry-mode loopback \
              ${GPG_PASSPHRASE:+--passphrase "$GPG_PASSPHRASE"} \
              --armor --output receipts/ROOT.txt.asc --detach-sign receipts/ROOT.txt
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install cosign
        if: ${{ secrets.GPG_PRIVATE_KEY == '' }}
        uses: sigstore/cosign-installer@v3

      - name: Sign ROOT (cosign keyless)
        if: ${{ secrets.GPG_PRIVATE_KEY == '' }}
        run: cosign sign-blob --yes --output-signature receipts/ROOT.txt.sig receipts/ROOT.txt

      - name: Upload signature
        uses: actions/upload-artifact@v4
        with:
          name: root-signature-${{ github.ref_name }}
          path: |
            receipts/ROOT.txt
            receipts/ROOT.txt.asc
            receipts/ROOT.txt.sig
          if-no-files-found: warn
