name: image-publish
on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker/**'
      - 'workbench/**'
      - 'package.json'
      - '.github/workflows/image-publish.yml'
    tags: [ 'v*' ]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
concurrency:
  group: image-publish
  cancel-in-progress: true
jobs:
  build-push:
    if: ${{ hashFiles('Dockerfile') != '' || hashFiles('docker/Dockerfile') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tags/labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/vaultsovereign/forge
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
