name: image-publish

on:
  push:
    branches: [main]
    tags: ['v*'] # publish semver tags as image tags
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: image-publish
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tags/labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/vaultsovereign/forge
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha

      - name: Build & Push (multi-arch + provenance)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true

  # Optional: post-publish security scan of the pushed :latest image
  trivy-after-publish:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Trivy (pushed image)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/vaultsovereign/forge:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
