name: lint-nightly

on:
  schedule:
    - cron: "17 2 * * *" # 02:17 UTC nightly
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-strict:
    name: Lint (strict mode - all warnings fail)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node & pnpm setup
        uses: ./.github/actions/node-pnpm-setup
        with:
          node-version: 20
          pnpm-version: 10.17.0

      - name: Lint (strict - fail on warnings)
        run: pnpm exec eslint -c .eslintrc.json . --ext .ts,.tsx --max-warnings=0
