name: pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'scripts/generate-docs-sitemap.mjs'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Keep the sitemap always fresh in docs/ before publishing
      - name: Generate docs sitemap
        run: node scripts/generate-docs-sitemap.mjs docs SITEMAP.md

      - name: Upload artifact (docs/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
